apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-youtube-auth
type: Opaque
data:
  client_secret.json: {{ .Values.secrets.clientSecret | b64enc | quote }}
  token.json: {{ .Values.secrets.token | b64enc | quote }}
